name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install PM2
      run: npm install pm2 -g
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        NODE_ENV: production
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Node.js and npm if not present
          if ! command -v node &> /dev/null; then
            echo "Installing Node.js and npm..."
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            
            # Verify installation
            node --version
            npm --version
          fi
          
          # Install PM2 globally if not present
          if ! command -v pm2 &> /dev/null; then
            echo "Installing PM2..."
            sudo npm install -g pm2
          fi
          
          export NODE_ENV=production
          # Create app directory if it doesn't exist
          mkdir -p ~/resume-server
          
          # Navigate to app directory
          cd ~/resume-server
          
          # Check if git repository exists
          if [ ! -d .git ]; then
            # First time deployment
            git init
            git remote add origin ${{ github.server_url }}/${{ github.repository }}.git
            git fetch origin
            git checkout -f main
          else
            # Subsequent deployments
            git fetch origin
            git reset --hard origin/main
          fi
          
          # Install dependencies and start/restart application
          npm install --production
          pm2 restart server || pm2 start server.js --name server --env production
